//Homework 0
// Members Kimson, Nathan, Kevin
// Q1
/*Write a program in which you will create two processes (not simulation):
A Producer process that generates and prints numbers.
A Consumer process that consumes the numbers generated by the Producer. 
Here, “consume” means the Consumer “obtains” or “receives” the numbers from 
Producer (by some IPC), and prints the numbers on stdout. 
*/
package main

import (
	"fmt"
	"os"
	"io"
	"time"
	"sync"
)

// Producer Generate
func producer() {
	// For loop:
	for i := 1; i <= 5; i++ {
		fmt.Printf("Producer: %d\n", i) 
		os.Stdout.Flush() 
}

// Consumer Grab
func consumer() {
	scanner := bufio.Scanner(os.Stdin)
	// Take value from Producer
	for scanner.Scan() {
		fmt.Printf("Consumer: %s\n", scanner.Text())
	}
}

func main() {
	consumer, producer := io.Pipe()	
	
	var wg sync.WaitGroup
	wg.Add(2)

}