//Homework 0
// Q1
/*Write a program in which you will create two processes (not simulation):
A Producer process that generates and prints numbers.
A Consumer process that consumes the numbers generated by the Producer. Here, “consume” means the Consumer “obtains” or “receives” the numbers from Producer (by some IPC), and prints the numbers on stdout. 
*/

// Q2 
/* Write a program to implement a stack of integers using an array of size 100. You can assume that your stack can never have 100 integers in the given workload. Your stack only needs to provide push and pop.
You should also implement a simple program to test your implementation (i.e., a series of pop and push).
*/
