//Homework 0
// Members Kimson, Nathan, Kevin
// Q1
/*Write a program in which you will create two processes (not simulation):
A Producer process that generates and prints numbers.
A Consumer process that consumes the numbers generated by the Producer. 
Here, “consume” means the Consumer “obtains” or “receives” the numbers from 
Producer (by some IPC), and prints the numbers on stdout. 
*/

// Producer Generate
// Producer Print
// Consumer Grab
// Consumer Print

